### ISSUE TITLE
cannot parse then unparse this: `hash["counter"] += 1`

### ISSUE THREAD

**Issue by catmando** [mbj/unparser#117]
parsing the above gives:

```ruby
 s(:op_asgn,
  s(:send,
    s(:send, nil, :hash), :[],
    s(:str, "counter")), :+,
  s(:int, 1)) 
```

and in unparser 2.8 this correctly produces `hash['counter'] += 1`

but in unparser 4.2 this produces `hash.[]('counter') += 1` 

which is illegal ruby syntax

**Comment by mbj** [comment]
@catmando You *very* likely updated to latest unparser without reading the Changelog, or the Readme.

> * Only support for the [modern AST](https://github.com/whitequark/parser/#usage) format

Note there is no `2.8` release, nor a 4.2 release.
