### ISSUE TITLE
Insufficient parenthesizing

### ISSUE THREAD

**Issue by akimd** [mbj/unparser#131]
Hi!

An input such as `return (true ? 1 : 2).to_s` is parsed|unparsed as

```ruby
return if true
  1
else
  2
end.to_s
```

which breaks the Ruby parser who sees a postfix `if` in the first line, and dies afterwards.  It should be unparsed as

```ruby
return (if true
  1
else
  2
end).to_s
```

Test case:
```ruby
require 'parser/current'
require 'unparser'

ast = Unparser.parse('return (true ? 1 : 2).to_s')
puts Unparser.unparse(ast)
```

**Comment by mbj** [comment]
@akimd Confirmed. You want to try to tackle it? It likely involves adding:

* An initial failing test case
* Changing the `#terminated?` for `if` to return `false` in case its parent is a `send`.

But this is just a rough assumption based on my memory. Still I'd be happy to accept a PR.

**Comment by mbj** [comment]
This will be fixed with the pending upgrade to ruby 2.7:

```
bundle exec unparser -e 'return (true ? 1 : 2).to_s' --verbose
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.1-compliant syntax, but you are running 2.7.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(string)
Original-Source:
return (true ? 1 : 2).to_s
Generated-Source:
return (if true
  1
else
  2
end).to_s
Original-Node:
(return
  (send
    (begin
      (if
        (true)
        (int 1)
        (int 2))) :to_s))
Generated-Node:
(return
  (send
    (begin
      (if
        (true)
        (int 1)
        (int 2))) :to_s))
Success: (string)
```

**Comment by akimd** [comment]
Great news!  Sorry for having dropped the ball...

**Comment by mbj** [comment]
> Great news! Sorry for having dropped the ball...

No worries, this is OSS.

BTW: Whats your unparser use case?

**Comment by akimd** [comment]
I'm mostly using the parser, and was doing some experiment with rewriting the asts.  I was using unparser to check the output.

Cheers!
