### ISSUE TITLE
Relax parser dependency

### ISSUE THREAD

**Issue by palkan** [mbj/unparser#138]
I understand the reason why parser is fixed to 2.6.3 (due to #129) but that also enforces other tools relying on parser to stick to the older version.

Unparser itself shouldn't break if used with the latest parser, 'cause the latter one is backward-compatible with older Rubies.

What about changing `~>` to `>=`?

**Comment by mbj** [comment]
@palkan This is a hard line to walk.

Given not 2.6 support is not really complete (well it was at a point before ruby started to add syntax). I think its fair to do so and note the current "expectations" in the readme.

**Comment by mbj** [comment]
@palkan I released `0.4.7` that depends on `parser >= 2.6.5`

**Comment by mbj** [comment]
@palkan Just curious what do you use unparser for?

**Comment by palkan** [comment]
Thanks a lot!

I'm using it in my transpiler project: https://github.com/ruby-next/ruby-next 🙂

And it currently requires a custom parser release. Hopefully, now I will be able to use the latest official versions.

And I'm also using it in Action Policy for pretty printing: https://github.com/palkan/action_policy/blob/master/lib/action_policy/utils/pretty_print.rb

So, thanks for your work!

**Comment by mbj** [comment]
@palkan Cool. BTW I see tildelift in your projects, what are your experiences?

I'd love to also acquire some sponsoring for unparser.

**Comment by palkan** [comment]
>  I see tildelift in your projects, what are your experiences?

Zero 🙂 _We don't have enough subscriber uses_
Honestly, I don't expect anything from it. OpenCollective seems to be a better alternative. Or GH Sponsors, which is quite similar but is still beta-like.

**Comment by mbj** [comment]
Haha. Yeah. I thought so.

I'd love to use GH sponsors, as its native to GH. But they did not reply yet to my application.
