### ISSUE TITLE
NoMethodError: undefined method `type' 

### ISSUE THREAD

**Issue by catmando** [mbj/unparser#141]
The following AST 
```ruby
s(:def, :wait,
  s(:args,
    s(:arg, :seconds)),
  s(:block,
    s(:send,
      s(:send,
        s(:const, nil, :Promise), :new), :tap),
    s(:args,
      s(:procarg0, :p)),
    s(:block,
      s(:send, nil, :after,
        s(:lvar, :seconds)),
      s(:args),
      s(:send,
        s(:lvar, :p), :resolve,
        s(:lvar, :seconds)))))
```
throws this error:
```
NoMethodError: undefined method `type' for :p:Symbol
```
on version `>= '0.4.6'` and `0.4.7.  (0.4.5 works fine.)

The precise code is as follows:

```ruby
Unparser.unparse Parser::CurrentRuby.parse(
  "def wait(seconds)\nPromise.new.tap { |p| after(seconds) { p.resolve(seconds) }}\nend"
)
```

Parser::CurrentRuby == Parser::Ruby26

(parser v 2.6.5.0)

**Comment by mbj** [comment]
@catmando BTW I can only reproduce this via your script if I enable the modern Ruby AST:

```
Parser::Builders::Default.emit_lambda   = true
Parser::Builders::Default.emit_procarg0 = true
Parser::Builders::Default.emit_encoding = true
Parser::Builders::Default.emit_index    = true
```

**Comment by mbj** [comment]
@catmando And more: The modern Ruby AST documentation is incomplete, which I just corrected with a [pull request to parser](https://github.com/whitequark/parser/pull/658).

To get your example parsing you need to switch on: `emit_arg_inside_procarg0`. Which than gets you to the actual modern AST format.

Or you use `Unaprser.parse` which uses a correctly configured parser internally.

**Comment by mbj** [comment]
@catmando I'm closing this as I'm confident your issue will be resolved once you activate the modern AST format. Please reopen if its not the case.

**Comment by catmando** [comment]
@mbj Thanks!  I can't remember why, but I needed modern AST.  However adding `emit_arg_inside_procarg0 = true` seems to make everything good.  Thanks so much for finding that.   

Also thanks for this Gem.  Its an absolute key component of a gem called hyper-spec.  Hyper-spec lets you write rspec expectations that will run on the client (using the Opal -> JS transpiler)

So you can write a spec like this:

```ruby
  it "can load isomorphic code using the isomorphic method" do
    isomorphic do  # this executes on both the client and the server
      def factorial(n)
        n==1 ? 1 : n * factorial(n-1)
      end
    end
    expect_evaluate_ruby do 
      factorial(5)  # this runs on the client in the browser (or headless browser)
    end.to eq(factorial(5))
  end
```

we use parser to parse the code and extract the code in the blocks, then use unparser to get in back into ruby, then the opal compiler to translate it to javascript.

We have 1000's of specs written like this, and it lets us code everything in ruby, so a huge thanks to you.
