### ISSUE TITLE
Block one arg comma

### ISSUE THREAD

**Issue by pilipenok** [mbj/unparser#240]
I found the issue when playing with ASTs generated by `parser` gem.
So I'm not sure the issue is in parser gem, or unparser, or both.

BTW,
https://github.com/mbj/unparser/blob/1834bcfef1d224a4b2b8d75c4372f4ea6a2e944f/lib/unparser/emitter/block.rb#L81
https://github.com/mbj/unparser/blob/1834bcfef1d224a4b2b8d75c4372f4ea6a2e944f/lib/unparser/emitter/args.rb#L10

Parser generates the same AST part `(args (arg :x))` for `|x|` and `|x,|`
Unparser always generates with comma `|x,|` for `(args (arg :x))`

The  problem is the case of array-like elements, i.e. when receiver is a hash or 2d-array:

Unparser result:
for `receiver = {a:1, b:2}`
expected without comma: `receiver.map { |x| x }` => `[[:a, 1], [:b, 2]]`
actual with comma: `receiver.map { |x,| x }` => `[:a, :b]`

for `receiver = [[1, 2], [3, 4]]`
expected without comma: `receiver.map { |x| x }` => `[[1, 2], [3, 4]]`
actual with comma: `receiver.map { |x,| x }` => `[1, 3]`

**Updated**: it turns out that the problem is much deeper,
thanks to @iliabylich's [post](https://ilyabylich.svbtle.com/my-favorite-parts-of-ruby#invisible-rest-argument_3) about invisible rest args and `excessed_comma` flag

So the question is: for this cases is it possible to generate the same code as the parser's ast was generated from?

**Comment by dgollahon** [comment]
@pilipenok Are you using parser to parse the ASTs? If so, you need to make sure you use the "modern" options (which include the `procarg0` node. `unparser` is capable of round-tripping these cases correctly:

```ruby
Unparser.unparse(Unparser.parse('receiver.map { |x| x }')) # => "receiver.map { |x|\n  x\n}"
Unparser.unparse(Unparser.parse('receiver.map { |x,| x }')) #=> "receiver.map { |x,|\n  x\n}"
```

Are you using an old version of `parser`, `unparser`, or a specific `parser` parsing configuration?

```ruby
Unparser.parse('receiver.map { |x| x }') # =>
# s(:block,
#   s(:send,
#     s(:send, nil, :receiver), :map),
#   s(:args,
#     s(:procarg0,
#       s(:arg, :x))),
#   s(:lvar, :x))
```

Your AST should show a `procarg0` node for the _non_ `,` case (as this is actually the exception to how args work).

**Comment by pilipenok** [comment]
thanks @dgollahon
didn't know about `procarg0`
will try it

**Comment by mbj** [comment]
@pilipenok So using the modern flags when parsing with `parser` produced an AST `unparser` handles correctly?

**Comment by pilipenok** [comment]
@mbj, 

Yes, with
```
Parser::Builders::Default.emit_procarg0            = true
Parser::Builders::Default.emit_arg_inside_procarg0 = true
```
parses/unparses `a.map { |x| x }` correctly to/from
```
(block
  (send
    (send nil :a) :map)
  (args
    (procarg0
      (arg :x)))
  (lvar :x))
```

Need both flags to be true.
If only `emit_procarg0` then parser generates '(procarg0 :x)' which is incorrect for unparser (undefined method `type' for :x :Symbol)

**Comment by mbj** [comment]
@pilipenok Yeah, its explicitly documented `unparser` *only* is expecting AST with all modernization flags set.

I cannot afford the time to make deep backwards compatibility `parser` currently offers.

**Comment by pilipenok** [comment]
@mbj, just for fun another attempt to convert python ast to ruby's one. 
Using unparser to get result ruby code which is actually not required but nice to see.

**Comment by mbj** [comment]
@pilipenok Cool. If you ever publish something let me know so I can link to it.

Unparser has lots of downloads, but I do not know which projects are using it, hence I'm asking everyone so I finally find the source of the activity ;)

**Comment by paulodeon** [comment]
Thanks for you work with this @mbj. We are using it at RailsRocket https://www.railsrocket.app/. A nocode builder that creates real apps.

**Comment by mbj** [comment]
@paulodeon wanna PR A use case listing to the repo for your case?

**Comment by mbj** [comment]
README, so its visible. I think there used to be a section of users.
