### ISSUE TITLE
Invalid parser for `Sequel.~(query)`

### ISSUE THREAD

**Issue by dgollahon** [mbj/unparser#280]
Related to #278 

```ruby
source = 'Sequel.~(query)'
# => "Sequel.~(query)"
Unparser.parse(source)
# => s(:send,
#   s(:const, nil, :Sequel), :~,
#   s(:send, nil, :query))
Unparser.unparse(Unparser.parse(source))
# => "~Sequel"
Unparser.parse(Unparser.unparse(Unparser.parse(source)))
# => s(:send,
#   s(:const, nil, :Sequel), :~)
```

**Comment by mbj** [comment]
Jep needs an extension of the same logic tree.

**Comment by mbj** [comment]
@dgollahon Fix released as 0.6.2. It amazes me that this language after *years* of having this library in production has more holes to discover. Ruby has a way to big syntatic core.

**Comment by mbj** [comment]
@dgollahon BTW a quick way to reduce this issues is: `bundle exec unparser -e 'Sequel.~(query)' --verbose` or similar. Much easier than to write a repro script. It even comes with an AST differ ;)

**Comment by dgollahon** [comment]
> @dgollahon BTW a quick way to reduce this issues is: bundle exec unparser -e 'Sequel.~(query)' --verbose or similar. Much easier than to write a repro script. It even comes with an AST differ ;)

Thanks for the tip! I thought there was something like that but I couldn't remember what it was so I did what I knew.

Thanks for the quick fix!
