### ISSUE TITLE
Feature request: `unparser validate` CLI command

### ISSUE THREAD

**Issue by dgollahon** [mbj/unparser#324]
It would be nice to have a CLI command where you could invoke `unparser` and verify that it is able to round-trip a source-file. This shouldn't be too complicated to build and would make building reproduction cases and opening issues easier. I often end up writing some ad-hoc ruby to do this if I suspect an `unparser` issue when `mutant` is behaving in surprising ways.

**Comment by mbj** [comment]
this is actually already present ;)

```
bundle exec unparser some-file.rb
```

options: `--verbose` and `-e` (to pass source directly) :P

**Comment by dgollahon** [comment]
Oh, cool, thanks.
