### ISSUE TITLE
0.0.17 Breaks 1.9.3 compatibility

### ISSUE THREAD

**Issue by nielsm** [mbj/unparser#37]
79c937798d3aec11b6d4ac5c75a233c0c6c724c4 Explicitly changes the ruby version requirement in the gemspec

**Comment by mbj** [comment]
@nielsm This was an intentional change. What I should do about?

**Comment by nielsm** [comment]
There are several other gems depending on unparser that do NOT require 2.0, so this is breaking all of them. We don't directly use it, but some gems we use depend on it and now break our gems. 

For such a breaking change, I'd suggest either a very different version number, or support either version of Ruby. 

Niels

**Comment by mbj** [comment]
> For such a breaking change, I'd suggest either a very different version number, or support either version of Ruby.

You notice the `0.0` prefix of the version number. And read the definition of semver on that numbers?

**Comment by mbj** [comment]
AKA: Below `1.0.0` I can break as much as I want at any time.

**Comment by nielsm** [comment]
I understand that it can change, just making a suggestion to reflect such a breaking change.  Understand too that if someone is using non exact versioning in a gem spec like ~>0.0.16, this version would still match, but break their code.  Changing it to 0.1.0 would prevent the breaking change in that case.

**Comment by mbj** [comment]
@nielsm Downstream authors can also use `= 0.0.16` to fix.

**Comment by mbj** [comment]
Actually I'd have changed to `0.1.x` in case I knew there are others using unparser. I thought [mutant](https://github.com/mbj/mutant) is the only client.

I'm considering to jank `0.0.17` and release `0.1.0` soonish.

**Comment by mbj** [comment]
There is quite some gems using it:

```
curl https://rubygems.org/api/v1/gems/unparser/reverse_dependencies.json
["reek","mutant","rspec-parameterized","outil","rewriter","active_mocker","proc_to_ast","metamorpher","zapata","attr_accessible2strong_params","specify","flood-capybara","unparser-cli_wrapper","zombie-killer","gemfile_arranger"]
```

Interesting.

**Comment by nielsm** [comment]
Yes and reverse dependencies only shows direct dependencies, not 2 or more removed, which would also be affected.  We worked around it by adding a direct dependency on 0.0.16, but that is very hacky, since we don't directly rely on it.

**Comment by mbj** [comment]
Released `0.2.0` and yanked `0.1.17`. Closing this issue.

**Comment by mbj** [comment]
@nielsm Out of curiosity how do you pull unparser dependency? I think you are not a mutant user since mutant is `>= 2.0.0` for month now.

**Comment by nielsm** [comment]
For us, it probably came from reek, but it is difficult to tell exactly or exclusively, since there is a lot of shared dependency.

**Comment by mbj** [comment]
I wounder what reek uses unparser for.

**Comment by mvz** [comment]
@mbj we use it to render fragments of ruby code in our smell messages.
