### ISSUE TITLE
Circular argument reference

### ISSUE THREAD

**Issue by ravensnowbird** [mbj/unparser#47]
Hi, I noticed this on my rails console ( 4.2.1 ) while booting up the server. Wanted to check if its a bug. 

/home/raven/.rvm/gems/ruby-2.2.2@startuphub/gems/unparser-0.1.16/lib/unparser/emitter.rb:449: warning: circular argument reference - body
/home/raven/.rvm/gems/ruby-2.2.2@startuphub/gems/unparser-0.1.16/lib/unparser/emitter.rb:497: warning: circular argument reference - node

**Comment by mbj** [comment]
@ravensnowbird Fixed long ago, use a recent release.
