### ISSUE TITLE
Set version of RSpec as development dependency in gemspec

### ISSUE THREAD

**Issue by alexdowad** [mbj/unparser#57]
I'm trying to run `rake ci`, and am getting an error from within the guts of RSpec about `uninitialized constant ProgressFormatter`.

First thing I notice, no specific version of RSpec is set as a development dependency.

**Comment by mbj** [comment]
@alexdowad Unparser depends on devtools that pulls rspec: https://github.com/mbj/unparser/blob/master/unparser.gemspec#L29

But unparser was not touched for month and once stable integrations likely are now stale. I'll fix that prior merging #55.

**Comment by alexdowad** [comment]
OK. I found that the RSpec error doesn't occur on 2.2 (it does on 2.3), haven't investigated in detail but it seems that it may be related to the use of `autoload` in RSpec. There are too many other problems I am more interested in solving, so I'm leaving this one here.

**Comment by mbj** [comment]
@alexdowad I'll get you a green master tomorrow. And I hate autoloads ;) Gonna publish / port my tools to an rspec replacement "soon".
