### ISSUE TITLE
Unparser's approach to emitting comments is fragile

### ISSUE THREAD

**Issue by alexdowad** [mbj/unparser#58]
When unparsing an AST, Unparser can take an optional array of `Parser::Source::Comment` objects. It is assumed that the comments all come from the same Ruby source file, and that they are sorted in order of occurrence.

When emitting code, Unparser tracks the source range (`Parser::Source::Range`) for the node last emitted. When the end of a line is reached, it looks at the comments, compares their source ranges to that of the node just emitted, and sees if there is a comment not yet emitted, which belongs at the end of the node.

This approach is really only good for one thing: round-tripping ASTs which were parsed from a single Ruby source file.

It breaks down if you take nodes which were parsed from different source files (or from code strings), combine them in a new AST, and unparse them.

It breaks down if you take an AST parsed from a file, modify some nodes, and then unparse it, since the newly synthesized nodes don't have source maps. (And neither should they -- there is nothing in the source buffer which corresponds to them in a meaningful way.)

It breaks down if you synthesize an AST completely from scratch, but want comments to appear in the source code which is produced from that AST.

It would be better if there was metadata attached to nodes indicating whether a comment appears directly after that node. That would be robust. When replacing nodes in an AST, you could copy the comment metadata over to the new nodes, and the comments would come out in the right place.

You could combine nodes which were parsed from different source files (or strings), and all the comments would come out in the right places.

You could synthesize ASTs from scratch, attach comment metadata wherever you liked, then unparse, and the comments would come out in the right places.

Unfortunately, `parser` doesn't attach that metadata to nodes. It does, however, have `Parser::Source::Comment::Associator`, which takes an AST and a comment array, and produces a hash relating AST nodes to adjacent comments.

A hash like that is much better than a comment array. If you combine nodes parsed from different sources into a new AST, you can simply merge the comment hashes. Easy. Flexible. Robust.

If you synthesize nodes, you can add entries to the comment hash as desired. Again: easy, flexible, and robust.

Or, if you are replacing nodes in an existing AST, you can remove the entry in the comment hash for the old node, and add an equivalent entry for the new node.

The problem is that this would be a backwards-incompatible change! Unless we added a new entry point... or just detected whether the `comments` parameter is an array or a hash?

**Comment by mbj** [comment]
I'm fine with backwards incompatible changes. Unparser is pre 1.x so semver is shifted. Bumping from `0.2.x` to `0.3.x` is totally fine for me to account for the different API.

**Comment by alexdowad** [comment]
How do you feel about passing in comments as a `{ node => [comments] }` hash rather than an array?

Perhaps as a convenience, if someone passes in a comment array returned by `Parser::CurrentRuby.parse_with_comments`, we can automatically run `Parser::Source::Comment::Associator` on it to get the hash?

**Comment by mbj** [comment]
I do not like convenience at all. When there is a better API, lets use it, bump vesion and kill the old immediately.

For better comment reproduction, do you need anything else than `node -> [comments]` API? Maybe we should than pass an object that does exactly that `#call(node) -> [comments]` avoiding primitive infection in the API.

By default we can pass an object that always unconditionally returns `[]` fixing branches in the implementation.

Nobody can forsee the best API, so it might be a good idea to start with passing the hash directly, and once the improvement works look into constrainin the provided API via wrapping the hash. Or leave the hash intact if the wrapper has more than a `#call`.

**Comment by alexdowad** [comment]
One complication: `Parser::AST::Node`s are immutable and hash by value, not identity... but metadata like source maps are not included in the hash code. This was a deliberate decision on the part of the designer, and it was a good decision, but it means that using a simple `{ node => [comments] }` hash doesn't work. You could have 2 different `(send nil :puts (lvar :a))` nodes, which come from completely different locations in the source, and have different comment metadata, but they will hash to the same key/val entry.

I think your idea of `#call(node)` is good: someone could pass something as straightforward as `proc { |node| comment_hash[node.object_id] }`, or they could use some custom class if desired.

**Comment by alexdowad** [comment]
I have made a lot of progress on this issue. It turns out that just `#call` is not enough -- we need to know if a comment appeared before or after a node, etc. I have introduced a new `Unparser::Comments` class which tracks the correspondence between AST nodes and comments. I think you will like it.

However, it turns out that my other PR related to parenthesizing arithmetic expressions needs to finish before this one -- because `visit_on_side` will be used by this one also. (It turns out that when emitting comments, you need to do things slightly different on the left side of a binary operator.)

**Comment by mbj** [comment]
> However, it turns out that my other PR related to parenthesizing arithmetic expressions needs to finish before this one -- because visit_on_side will be used by this one also. (It turns out that when emitting comments, you need to do things slightly different on the left side of a binary operator.)

You could rebase this PR on top of the other one, I'll remember to merge them in order.

**Comment by mbj** [comment]
@alexdowad As this is not an actionable issue, and no input pattern is currently reported that breaks commend reproduction I'll close this issue.

If you want to work on improving the flexibiltiy of the comment reproduction, be my guest. But I assume you stopped thinking about using unparser in rubocop so its likely also in your intention to close this issue.
