### ISSUE TITLE
Minor release from 0.2.4 to 0.2.5 dropped Ruby 2.0 support

### ISSUE THREAD

**Issue by henrylawson** [mbj/unparser#65]
I have a project that indirectly requires this gem through another gem.

With the release of 0.2.5 from 0.2.4 (a minor release) support for [Ruby 2.0 was dropped from the Gemspec](https://github.com/mbj/unparser/commit/5d982ec2f0683f4ff8061b46c8b8e165905ab815), this meant that even though the dependent Gems were using a pessimistic constraint (http://guides.rubygems.org/patterns/) on their versioning, doing a `bundle update` pulled in this Gem.

The workaround for my project is to explicitly require '0.2.4' in my Gemfile, even though this Gem is included indirectly. Ideally a breaking API change such as this should be a bigger bump in version number (http://semver.org/) to allow including Gems with pessimistic requires to avoid the update.

This isn't a huge issue, but I thought I would raise an issue here incase you were not aware of the implications.

**Comment by mbj** [comment]
Again: As long I'm in `0.y` I'll NOT follow semver as per definition of semver. I do not recommend using `~> 0.y` style.

To quote the semver manifesto, from semver.org

> 4: Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by mbj** [comment]
Ohh and:

> 1. Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive.

There is not even an `@api public` in the entire code base, nor a statement that the supported runtime Ruby version is part of it. There is a statement the Ruby syntax for 2.0 can be reproduced. Which is entirely true running `> 2.0`.

**Comment by henrylawson** [comment]
I had missed the point about 0.y.z being for initial development, thanks for pointing it out.

My definition of API is very vague, sorry about that, as the update happened in the gemspec bundler raises an error if the runtime does not meet the requirements specified in it. So while the ruby code might still run on 2.0, on `bundle install` the below error is raised.

```
Installing unparser 0.2.5

Gem::InstallError: unparser requires Ruby version >= 2.1.
```

Thanks for taking the time to the review the issue and thanks for maintaining and updating this useful gem!

**Comment by mbj** [comment]
While it might (and actually likely) works under 2.0 I do not regularly test it there. My personal policy is not to put the users of my libs at risk for "silent" breakage.

Also I need to effectively use my very limited OSS time, which results in decisions like dropping 2.0 to reduce the number of dimensions I've to care about. Also dropping 2.0 allows me to use syntax that is not supported there.

**Comment by mbj** [comment]
> I had missed the point about 0.y.z being for initial development, thanks for pointing it out.

I use `~> 0.x.z` style dependencies for that reason for all `0.y` dependencies to reduce the risk a bit.

**Comment by obfuscoder** [comment]
Breaking compatibility with version change in third part is still not a good idea. For instance I use reek which has (in version 2.2.1) a dependency to unparser with ~> 0.2.2. Anything more restrictive would lock the dependency to a specific version and would then conflict with other gems having a dependency to a different strict version of unparser. This makes the gem more or less useless to depend upon if I can't even trust the compatibility when the patch version part changes. Do you really want to discourage other developers from depending on this gem until it reaches version 1.x?

**Comment by mbj** [comment]
> Breaking compatibility with version change in third part is still not a good idea.

I've outlined my reasons above and do not think repeating them would add to this discussion. But the following: I invite you to fork this gem and do better. Maybe you have more OSS time than me to support more rubies, and to provide an 1.0 ready gem.
