### ISSUE TITLE
Missing emitters?

### ISSUE THREAD

**Issue by evdubs** [mbj/unparser#85]
I am trying to use the following code:

```
require 'parser/current'
require 'unparser'

Parser::Builders::Default.emit_lambda   = true
Parser::Builders::Default.emit_procarg0 = true
Parser::Builders::Default.emit_encoding = true
Parser::Builders::Default.emit_index    = true

parsed_file = Parser::CurrentRuby.parse("def a(b, c)
  d[b] = c
end")
puts parsed_file
puts Unparser.unparse(parsed_file)
```

I get the error:

`No emitter for node: :indexasgn`

Also, with the following:

```
parsed_file = Parser::CurrentRuby.parse("def a(b, c)
  d = c[b]
end")
```

I get:

`No emitter for node: :index`

I suppose unparser will need indexasgn and index emitters? Or maybe I am doing something wrong?

**Comment by mbj** [comment]
These are relatively new parser nodes, which unparser does not yet support.

PRs welcome.

**Comment by evdubs** [comment]
Do you have any tips or advice for how to add these emitters? Maybe an emitter it should be modeled off of?

**Comment by mbj** [comment]
@evdubs Just look at the existing emitters. Many nodes are different for evaluating ruby, but not for generating concrete syntax. It could be an existing emitter can handle some of these cases already.

**Comment by evdubs** [comment]
Nevermind. The code `Parser::Builders::Default.emit_index    = true` was allowing this to be emitted. By not including this, I can parse and unparse.

**Comment by mbj** [comment]
@evdubs I still take PRs, unparser historically handles the parser defaults. I'd be happy to also support the optional nodes.

**Comment by mbj** [comment]
@evdubs Note that as per unparser-0.4.0 unparser only supports the modern AST format. The one which you originally reported for.

**Comment by evdubs** [comment]
@mbj thanks for the heads up.
